float:
  any:
  - base_args: ['@metric']
    constructor: MRPT
    disabled: false
    docker_tag: ann-benchmarks-mrpt
    module: ann_benchmarks.algorithms.mrpt
    name: mrpt
    run_groups:
      mrpt:
        args: ['@count']
        query_args: [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.925, 0.95,
            0.97, 0.98, 0.99, 0.995]]
