float:
  any:
  - base_args: ['@metric']
    constructor: Sptag
    disabled: false
    docker_tag: ann-benchmarks-sptag
    module: ann_benchmarks.algorithms.sptag
    name: sptag
    run_groups:
      sptag:
        args: [[BKT, KDT]]
        query_args: [[100, 200, 400, 1000, 2000, 4000]]
