sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  - LIBRARY=annoy DATASET=random-xs-20-angular
  - LIBRARY=dolphinn DATASET=random-xs-20-angular
  - LIBRARY=faiss  DATASET=random-xs-20-angular
  - LIBRARY=flann DATASET=random-xs-20-angular
  - LIBRARY=kgraph DATASET=random-xs-20-angular
  - LIBRARY=mrpt DATASET=random-xs-20-angular
  - LIBRARY=nearpy DATASET=random-xs-20-angular
  - LIBRARY=ngt DATASET=random-xs-20-angular
  - LIBRARY=nmslib DATASET=random-xs-20-angular
  - LIBRARY=hnswlib DATASET=random-xs-20-angular
  - LIBRARY=panns DATASET=random-xs-20-angular
  - LIBRARY=puffinn DATASET=random-xs-20-angular
  - LIBRARY=pynndescent DATASET=random-xs-20-angular
  - LIBRARY=rpforest DATASET=random-xs-20-angular
  - LIBRARY=sklearn DATASET=random-xs-20-angular
  - LIBRARY=sptag DATASET=random-xs-20-angular
  - LIBRARY=mih DATASET=random-xs-16-hamming
  - LIBRARY=datasketch DATASET=random-s-jaccard

before_install:
  - pip install -r requirements.txt
  - python install.py

script:
  - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --timeout 300
  - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --batch --timeout 300
  - sudo chmod -R 777 results/
  - python plot.py --dataset $DATASET --output plot.png
  - python plot.py --dataset $DATASET --output plot-batch.png --batch
  - python -m unittest test/test-metrics.py
  - python -m unittest test/test-jaccard.py
  - python create_website.py --outputdir . --scatter --latex
