float:
  any:
  - base_args: ['@metric', Float, 0.1]
    constructor: QG
    disabled: false
    docker_tag: ann-benchmarks-qg_ngt
    module: ann_benchmarks.algorithms.qg_ngt
    name: NGT-qg
    run_groups:
      s2000-e0.02:
        args: [{edge: 100, epsilon: 0.02, indegree: 120, max_edge: 96, outdegree: 64,
            sample: 2000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      s20000-e0.1:
        args: [{edge: 100, indegree: 120, max_edge: 96, outdegree: 64, sample: 20000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      s4000-e0.02:
        args: [{edge: 100, epsilon: 0.02, indegree: 120, max_edge: 96, outdegree: 64,
            sample: 4000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      s4000-e0.04:
        args: [{edge: 100, epsilon: 0.04, indegree: 120, max_edge: 96, outdegree: 64,
            sample: 4000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      s4000-e0.06:
        args: [{edge: 100, epsilon: 0.06, indegree: 120, max_edge: 96, outdegree: 64,
            sample: 4000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      s4000-e0.08:
        args: [{edge: 100, epsilon: 0.08, indegree: 120, max_edge: 96, outdegree: 64,
            sample: 4000}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
