float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: Milvus
    disabled: false
    docker_tag: ann-benchmarks-milvus
    module: ann_benchmarks.algorithms.milvus
    name: Milvus(Knowhere)
    run_groups:
      HNSW:
        args:
          M: [4, 8, 12, 16, 24, 36, 48, 64, 96]
          efConstruction: 500
        query_args: [[10, 15, 20, 25, 30, 35, 40, 50, 60, 80, 120, 200, 400, 600,
            800]]
