float:
  any:
  - base_args: ['@metric']
    constructor: KDTree
    disabled: true
    docker_tag: ann-benchmarks-kdtree
    module: ann_benchmarks.algorithms.kdtree
    name: kd
    run_groups:
      ball:
        args: [[10, 20, 40, 100, 200, 400, 1000]]
