float:
  any:
  - base_args: ['@metric', Float, 0.1]
    constructor: QSG
    disabled: false
    docker_tag: ann-benchmarks-qsg_ngt
    module: ann_benchmarks.algorithms.qsg_ngt
    name: qsgngt
    run_groups:
      K-200-100:
        args: [{edge: 100, epsilon: 0.1, ifES: 1, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [200, 200, 15, 10, 100], paramS: [100, 100, 60], range: 200, rangeMax: 200,
            sample: 20000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-1:
        args: [{edge: 100, epsilon: 0.1, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 175, rangeMax: 175,
            sample: 20000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-2:
        args: [{edge: 100, epsilon: 0.04, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 175, rangeMax: 175,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-3:
        args: [{edge: 100, epsilon: 0.02, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 175, rangeMax: 175,
            sample: 2000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-4:
        args: [{edge: 100, epsilon: 0.04, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 100, rangeMax: 300,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-5:
        args: [{edge: 100, epsilon: 0.02, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 100, rangeMax: 300,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-6:
        args: [{edge: 100, epsilon: 0.02, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 175, rangeMax: 175,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-7:
        args: [{edge: 100, epsilon: 0.08, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 200, rangeMax: 200,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-8:
        args: [{edge: 100, epsilon: 0.04, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 200, rangeMax: 200,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-60-9:
        args: [{edge: 100, epsilon: 0.02, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 200, rangeMax: 200,
            sample: 4000, searchA: 400, threshold: 60}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
      cos-89:
        args: [{edge: 100, epsilon: 0.08, ifES: 0, indegree: 120, max_edge: 96, outdegree: 64,
            paramE: [400, 400, 12, 10, 250], paramS: [100, 100, 60], range: 200, rangeMax: 200,
            sample: 4000, searchA: 400, threshold: 89}]
        query_args: [[[0.0, 0.9], [0.0, 0.95], [0.0, 0.98], [0.0, 1.0], [1.2, 0.9],
            [1.5, 0.9], [2.0, 0.9], [3.0, 0.9], [1.2, 0.95], [1.5, 0.95], [2.0, 0.95],
            [3.0, 0.95], [1.2, 0.98], [1.5, 0.98], [2.0, 0.98], [3.0, 0.98], [1.2,
              1.0], [1.5, 1.0], [2.0, 1.0], [3.0, 1.0], [5, 1.0], [10, 1.0], [20,
              1.0], [1.2, 1.02], [1.5, 1.02], [2.0, 1.02], [3.0, 1.02], [2, 1.04],
            [3, 1.04], [5, 1.04], [8, 1.04]]]
