float:
  euclidean:
  - base_args: ['@metric']
    constructor: TileDBIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-ivf-flat
    run_groups:
      IVFFLAT:
        args: 
          nlist: [[512, 1024, 2048, 4096, 8192]]
        # n_probe:
        query_args: [[1, 5, 10, 50, 100, 200]]

  - base_args: ['@metric']
    constructor: TileDBFlat
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-flat
    run_groups:
      FLAT:
        args:
            placeholder: [0]

  - base_args: ['@metric']
    constructor: TileDBVamana
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-vamana
    run_groups:
      VAMANA:
        args:
            placeholder: [0]
        # opt_l:
        query_args: [[20, 40, 60, 80, 100, 120]]
