bit:
  hamming:
  - base_args: ['@metric']
    constructor: PyNNDescent
    disabled: false
    docker_tag: ann-benchmarks-pynndescent
    module: ann_benchmarks.algorithms.pynndescent
    name: pynndescent
    run_groups:
      NN-120:
        arg_groups: [{diversify_prob: [0.0, 1.0], leaf_size: 80, n_neighbors: [120],
            pruning_degree_multiplier: [2.0, 2.5]}]
        args: {}
        query_args: [[0.08, 0.16, 0.2, 0.24, 0.28, 0.32, 0.36]]
      NN-20:
        arg_groups: [{diversify_prob: [0.75, 1.0], leaf_size: 32, n_neighbors: [20],
            pruning_degree_multiplier: [1.0, 1.5]}]
        args: {}
        query_args: [[0.0, 0.01, 0.02, 0.04, 0.08, 0.12, 0.16]]
      NN-40:
        arg_groups: [{diversify_prob: [0.5, 1.0], leaf_size: 48, n_neighbors: [40],
            pruning_degree_multiplier: [1.5, 2.0]}]
        args: {}
        query_args: [[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24]]
      NN-80:
        arg_groups: [{diversify_prob: [0.25, 1.0], leaf_size: 64, n_neighbors: [80],
            pruning_degree_multiplier: [1.75, 2.25]}]
        args: {}
        query_args: [[0.0, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32]]
  jaccard:
  - base_args: ['@metric']
    constructor: PyNNDescent
    disabled: false
    docker_tag: ann-benchmarks-pynndescent
    module: ann_benchmarks.algorithms.pynndescent
    name: pynndescent
    run_groups:
      NN-120:
        arg_groups: [{diversify_prob: [1.0, 0.125], leaf_size: 80, n_neighbors: 120,
            pruning_degree_multiplier: 1.0}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22]]
      NN-20:
        arg_groups: [{diversify_prob: [0.75, 1.0], leaf_size: 30, n_neighbors: 20,
            pruning_degree_multiplier: 1.0}]
        args: {}
        query_args: [[0.0, 0.01, 0.02, 0.03, 0.04, 0.06, 0.08, 0.12, 0.16, 0.2]]
      NN-40:
        arg_groups: [{diversify_prob: [0.5, 1.0], leaf_size: 30, n_neighbors: 40,
            pruning_degree_multiplier: 1.0}]
        args: {}
        query_args: [[0.0, 0.01, 0.02, 0.03, 0.04, 0.06, 0.08, 0.12, 0.16, 0.2]]
      NN-80:
        arg_groups: [{diversify_prob: [1.0, 0.25], leaf_size: 60, n_neighbors: 80,
            pruning_degree_multiplier: 1.0}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.06, 0.08, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22]]
float:
  angular:
  - base_args: ['@metric']
    constructor: PyNNDescent
    disabled: false
    docker_tag: ann-benchmarks-pynndescent
    module: ann_benchmarks.algorithms.pynndescent
    name: pynndescent
    run_groups:
      NN-120-accurate:
        arg_groups: [{diversify_prob: 0.125, leaf_size: 35, n_neighbors: 120, pruning_degree_multiplier: 2.5}]
        args: {}
        query_args: [[0.16, 0.2, 0.24, 0.28, 0.32, 0.36]]
      NN-120-fast:
        arg_groups: [{diversify_prob: 1.0, leaf_size: 20, n_neighbors: 120, pruning_degree_multiplier: 2.5}]
        args: {}
        query_args: [[0.0, 0.04, 0.08, 0.16, 0.2, 0.24, 0.28, 0.32]]
      NN-20:
        arg_groups: [{diversify_prob: [1.0], leaf_size: 20, n_neighbors: [20], pruning_degree_multiplier: [
              0.5, 1.0]}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12]]
      NN-40:
        arg_groups: [{diversify_prob: [0.5, 1.0], leaf_size: 25, n_neighbors: [40],
            pruning_degree_multiplier: [1.5]}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16]]
      NN-80-accurate:
        arg_groups: [{diversify_prob: 0.25, leaf_size: 30, n_neighbors: 80, pruning_degree_multiplier: 2.0}]
        args: {}
        query_args: [[0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 0.36]]
      NN-80-fast:
        arg_groups: [{diversify_prob: 1.0, leaf_size: 20, n_neighbors: 80, pruning_degree_multiplier: 2.0}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24]]
  euclidean:
  - base_args: ['@metric']
    constructor: PyNNDescent
    disabled: false
    docker_tag: ann-benchmarks-pynndescent
    module: ann_benchmarks.algorithms.pynndescent
    name: pynndescent
    run_groups:
      NN-10:
        arg_groups: [{diversify_prob: 1.0, leaf_size: 24, n_neighbors: 10, pruning_degree_multiplier: [
              0.5, 1.0]}]
        args: {}
        query_args: [[0.0, 0.01, 0.02, 0.03, 0.04, 0.06, 0.08, 0.1, 0.12]]
      NN-20:
        arg_groups: [{diversify_prob: 1.0, leaf_size: 24, n_neighbors: 20, pruning_degree_multiplier: [
              0.75, 1.5]}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.2]]
      NN-40:
        arg_groups: [{diversify_prob: [0.0, 1.0], leaf_size: 36, n_neighbors: 40,
            pruning_degree_multiplier: [1.0, 2.0]}]
        args: {}
        query_args: [[0.0, 0.02, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32]]
      NN-60:
        arg_groups: [{diversify_prob: 0.0, leaf_size: 48, n_neighbors: 60, pruning_degree_multiplier: [
              2.0, 3.0]}]
        args: {}
        query_args: [[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 0.36]]
