name: ANN benchmarks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - library: annoy
            dataset: random-xs-20-angular
          - library: dolphinn
            dataset: random-xs-20-angular
          - library: faiss
            dataset: random-xs-20-angular
          - library: flann
            dataset: random-xs-20-angular
          - library: kgraph
            dataset: random-xs-20-angular
          - library: milvus
            dataset: random-xs-20-angular
          - library: mrpt
            dataset: random-xs-20-angular
          - library: n2
            dataset: random-xs-20-angular
          - library: nearpy
            dataset: random-xs-20-angular
          - library: ngt
            dataset: random-xs-20-angular
          - library: nmslib
            dataset: random-xs-20-angular
          - library: hnswlib
            dataset: random-xs-20-angular
          - library: puffinn
            dataset: random-xs-20-angular
          - library: pynndescent
            dataset: random-xs-20-angular
          - library: rpforest
            dataset: random-xs-20-angular
          - library: sklearn
            dataset: random-xs-20-angular
          - library: sptag
            dataset: random-xs-20-angular
          - library: mih
            dataset: random-xs-16-hamming
          - library: datasketch
            dataset: random-s-jaccard
          - library: scann
            dataset: random-xs-20-angular
          - library: elasticsearch
            dataset: random-xs-20-angular
          - library: elastiknn
            dataset: random-xs-20-angular
          - library: opensearchknn
            dataset: random-xs-20-angular
          - library: diskann
            dataset: random-xs-20-angular
          - library: puffinn
            dataset: random-s-jaccard
          - library: pynndescent
            dataset: random-s-jaccard
          - library: vespa
            dataset: random-xs-20-angular
          - library: scipy
            dataset: random-xs-20-angular
          - library: vald
            dataset: random-xs-20-angular
      fail-fast: false

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Install various apt packages
      run: sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        python3 install.py

      env:
        LIBRARY: ${{ matrix.library }}
        DATASET: ${{ matrix.dataset }}
    
    - name: Run the benchmark
      run: |
        python3 run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --timeout 300
        python3 run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset $DATASET --run-disabled --batch --timeout 300
        sudo chmod -R 777 results/
        python3 plot.py --dataset $DATASET --output plot.png
        python3 plot.py --dataset $DATASET --output plot-batch.png --batch
        python3 -m unittest test/test-metrics.py
        python3 -m unittest test/test-jaccard.py
        python3 create_website.py --outputdir . --scatter --latex

      env:
        LIBRARY: ${{ matrix.library }}
        DATASET: ${{ matrix.dataset }}
